# Generated by Django 4.2.17 on 2024-12-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
