# Generated by Django 4.2.17 on 2024-12-15 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_region_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contact.contact')),
            ],
            options={
                'verbose_name': 'Contact Answer',
                'verbose_name_plural': 'Contact Answers',
            },
        ),
    ]
