# Generated by Django 4.2.17 on 2024-12-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='verification_code',
            field=models.CharField(max_length=5, null=True, verbose_name='verification_code'),
        ),
    ]
